apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-bootstrap-kind
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Michigety/k8s_cluster_bootstrap.git
    targetRevision: main
    path: kind/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
